### ISSUE TITLE
Hyperlink inside bold text doesn't render

### ISSUE THREAD

**Issue by breenbob** [0xc3u/Indiko.Maui.Controls.Markdown#11] opened 2024-09-06 13:36 UTC
Found an issue where Hyperlinks don't render if inside bold text, and looking at the implementation, probably any other valid tags too, e.g.

`**Some bold text with a [link](https://www.github.com) blah blah**`

The text turns bold, but the link doesn't render. Move it outside the bold text and link works fine:
`**Some bold text with a** [link](https://www.github.com) **blah blah**`

Looking at the implementation it seems maybe this is a limitation of fact that each part of a line can only relate to one markdown feature. Guess it would have to rerun regular exp again on each individual part to resolve, which may affect performance?

Love the package by the way.

**Comment by 0xc3u** [comment] 2024-09-18 07:41
Thank you so much for taking the time to report this issue and for your kind words about the package! 🙏

You were absolutely right in identifying the problem with hyperlinks inside bold text, and your insight into how the implementation handles different markdown features was spot on. We've addressed this limitation, and the issue is now fixed in version 1.0.13.

Thanks again for your valuable feedback, and we're glad you're enjoying the package! Please feel free to reach out if you encounter any further issues or have any suggestions for improvement. 

Happy coding! 🎉

**Closed by 0xc3u** 2024-09-18 07:41 UTC
